/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Component01 {
    }
    interface Component02 {
    }
    interface MusangoComponent {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLComponent01Element extends Components.Component01, HTMLStencilElement {
    }
    var HTMLComponent01Element: {
        prototype: HTMLComponent01Element;
        new (): HTMLComponent01Element;
    };
    interface HTMLComponent02Element extends Components.Component02, HTMLStencilElement {
    }
    var HTMLComponent02Element: {
        prototype: HTMLComponent02Element;
        new (): HTMLComponent02Element;
    };
    interface HTMLMusangoComponentElement extends Components.MusangoComponent, HTMLStencilElement {
    }
    var HTMLMusangoComponentElement: {
        prototype: HTMLMusangoComponentElement;
        new (): HTMLMusangoComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "component-01": HTMLComponent01Element;
        "component-02": HTMLComponent02Element;
        "musango-component": HTMLMusangoComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Component01 {
    }
    interface Component02 {
    }
    interface MusangoComponent {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "component-01": Component01;
        "component-02": Component02;
        "musango-component": MusangoComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-01": LocalJSX.Component01 & JSXBase.HTMLAttributes<HTMLComponent01Element>;
            "component-02": LocalJSX.Component02 & JSXBase.HTMLAttributes<HTMLComponent02Element>;
            "musango-component": LocalJSX.MusangoComponent & JSXBase.HTMLAttributes<HTMLMusangoComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
