/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomCheckbox {
    }
}
declare global {
    interface HTMLCustomCheckboxElement extends Components.CustomCheckbox, HTMLStencilElement {
    }
    var HTMLCustomCheckboxElement: {
        prototype: HTMLCustomCheckboxElement;
        new (): HTMLCustomCheckboxElement;
    };
    interface HTMLElementTagNameMap {
        "custom-checkbox": HTMLCustomCheckboxElement;
    }
}
declare namespace LocalJSX {
    interface CustomCheckbox {
    }
    interface IntrinsicElements {
        "custom-checkbox": CustomCheckbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-checkbox": LocalJSX.CustomCheckbox & JSXBase.HTMLAttributes<HTMLCustomCheckboxElement>;
        }
    }
}
